elmo:
  version: "@project.version@"
  sms:
    supported: true
  initial-new-member-id: 1
  admin-member-id: 1
  car-sharing:
    max-hours: 48
    max-reservations: 3
  cors:
    allowedHeaders:
    - '*'
    allowedMethods:
    - OPTIONS
    - GET
    - HEAD
    - PUT
    - POST
    - DELETE
    - PATCH
    maxAge: 43200
  passenger-service:
    days-for-initial-shift-creation: 90
    shifts:
      MONDAY:
        - start: '07:00:00'
          end: '10:00:00'
        - start: '10:00:00'
          end: '13:00:00'
        - start: '13:00:00'
          end: '16:00:00'
        - start: '16:00:00'
          end: '19:00:00'
      TUESDAY:
        - start: '07:00:00'
          end: '10:00:00'
        - start: '10:00:00'
          end: '13:00:00'
        - start: '13:00:00'
          end: '16:00:00'
        - start: '16:00:00'
          end: '19:00:00'
      WEDNESDAY:
        - start: '07:00:00'
          end: '10:00:00'
        - start: '10:00:00'
          end: '13:00:00'
        - start: '13:00:00'
          end: '16:00:00'
        - start: '16:00:00'
          end: '19:00:00'
      THURSDAY:
        - start: '07:00:00'
          end: '10:00:00'
        - start: '10:00:00'
          end: '13:00:00'
        - start: '13:00:00'
          end: '16:00:00'
        - start: '16:00:00'
          end: '19:00:00'
      FRIDAY:
        - start: '07:00:00'
          end: '10:00:00'
        - start: '10:00:00'
          end: '13:00:00'
        - start: '13:00:00'
          end: '16:00:00'
        - start: '16:00:00'
          end: '19:00:00'
server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: elmo
    # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
    spa-default-file: classpath:/static/index.html
  main:
    allow-bean-definition-overriding: true
  mvc:
    # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
    throw-exception-if-no-handler-found: true
  resources:
    # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
    add-mappings: false
  session:
    store-type: none
  liquibase:
    change-log: classpath:liquibase/master.yml
  jpa:
    open-in-view: false
  datasource:
    type: at.elmo.config.db.NotificationsAwareHikariDataSource
    hikari:
      maximum-pool-size: 10
      auto-commit: false
      minimum-idle: 0
      max-lifetime: 600000 # Build new connections every 10 minutes.
      idle-timeout: 180000 # Release new connections after 3 minutes of inactivity.
      leak-detection-threshold: 6000 # TODO determine a good value
      data-source-properties:
      defaultRowPrefetch: 100
  freemarker:
    template-loader-path: classpath:templates
springdoc:
  api-docs:
    enabled: false
camunda:
  bpm:
    default-number-of-retries: 1
    job-execution:
      wakeup: true
      core-pool-size: 2
      max-pool-size: 2
      wait-time-in-millis: 2500
      max-wait: 20000
    generic-properties:
      properties:
        historyCleanupBatchWindowStartTime: '22:00'
        historyCleanupBatchWindowEndTime: '04:00'
        historyCleanupBatchSize: 100
        initializeTelemetry: false
    authorization:
      enabled: false
    default-serialization-format: application/xstream
    database:
      schema-update: false
      jdbc-batch-processing: true
    metrics:
      enabled: true
      db-reporter-activate: false
    webapp:
      index-redirect-enabled: false
  telemetry:
    enabled: false
  xstream-serialization:
    allowed-types:
    - at.elmo.**
logging:
  level:
    liquibase.hub: ERROR
    # suppress warnings on loosing SSE connection due to user closed the browser
    org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver: ERROR
    # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
    org.springframework.web.servlet.PageNotFound: ERROR
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
    org.springframework.web.servlet.NoHandlerFoundException: FATAL

translations:
  general:
    en:
      passengerAgreement: Agreement-Passenger
      driverAgreement: Agreement-Driver
      dateFormat: MM/dd/yyyy
      salutation:
        MALE: "Mr."
        FEMALE: "Mrs."
        OTHER: ""
      payment:
        MONTHLY: "monthly"
        ANNUALLY: "annually"
        NONE: ""
      roleShortcuts:
        PASSENGER: P
        DRIVER: D
        MANAGER: M
        ADMIN: A
    de:
      passengerAgreement: Anmeldeformular-Passagier
      driverAgreement: Anmeldeformular-Fahrer
      dateFormat: dd.MM.yyyy
      salutation:
        MALE: "Herr"
        FEMALE: "Frau"
        OTHER: ""
      payment:
        MONTHLY: "Monatlich"
        ANNUALLY: "Jährlich"
        NONE: ""
      roleShortcuts:
        PASSENGER: P
        DRIVER: F
        MANAGER: M
        ADMIN: V
  downloadMembers:
    en:
      members: Members
      memberId: Member ID
      type: Type
      salutation: Salutation
      title: Title
      lastName: Lastname
      firstName: Firstname
      birthdate: Birthdate
      street: Street
      zip: ZIP
      city: City
      email: eMail
      phoneNumber: Phone
      comment: Comment
      iban: IBAN
      payment: Payment
      hoursServedPassengerService: Passenger-S.
      hoursConsumedCarSharing: Car-Sharing
    de:
      members: Mitglieder
      memberId: Mitgliedsnummer
      type: Typ
      salutation: Anrede
      title: Titel
      lastName: Nachname
      firstName: Vorname
      birthdate: Geburtstag
      street: Straße
      zip: PLZ
      city: Ort
      email: eMail
      phoneNumber: Telefon
      comment: Kommenatar
      iban: IBAN
      payment: Zahlung
      hoursServedPassengerService: Fahrtendienst
      hoursConsumedCarSharing: Car-Sharing

---
spring:
  config:
    activate:
      on-profile: "!local"
  data:
    r2dbc:
      repositories:
        enabled: false
