spring:
   application:
      name: elmo-gf
      # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
      spa-default-file: classpath:/static/index.html
   mvc:
      # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
      throw-exception-if-no-handler-found: true
   resources:
      # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
      add-mappings: false

elmo:

logging:
  level:
    # see de.mhb.commons.spa.SpaNoHandlerFoundExceptionHandler
    org.springframework.web.servlet.PageNotFound: ERROR
