openapi: 3.0.0
info:
  description: Administration API
  version: '1.0'
  title: administration
servers:
  - url: /api/v1.0

security:
  - JWT: []

paths:
  /administration/member-onboarding/{applicationId}/take-over:
    put:
      tags:
        - administration
      summary: as a member of management board take-over application from member
      operationId: takeoverMemberOnboardingApplication
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: string
      responses:
        200:
          description: Takeover successful
        400:
          description: application is in wrong status
  /administration/member-onboarding/{applicationId}:
    get:
      tags:
        - administration
      summary: get a member onboarding application
      operationId: getMemberOnboardingApplication
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: string
      responses:
        200:
          description: The updated member onboarding application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberApplication' 
    put:
      tags:
        - administration
      summary: update a member onboarding application
      operationId: updateMemberOnboardingApplication
      parameters:
        - in: path
          name: applicationId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMemberOnboarding'
      responses:
        200:
          description: The updated member onboarding application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberApplication' 
  /administration/member-onboarding:
    get:
      tags:
        - administration
      summary: number of all member onboardings of status IN_PROGRESS
      operationId: getCountOfInprogressMemberOnboardings
      responses:
        200:
          description: Count of all member onboardings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountOfInprogressMemberOnboardings'
    post:
      tags:
        - administration
      summary: all member onboarding applications
      operationId: getMemberOnboardingApplications
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            format: int32
        - in: query
          name: pageSize
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: All member onboardings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberOnboardingApplications' 
  /administration/member:
    get:
      tags:
        - administration
      summary: number of all active members
      operationId: getCountOfActiveMembers
      responses:
        200:
          description: Count of all active members
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountOfActiveMembers'
    post:
      tags:
        - administration
      summary: all members
      operationId: getMembers
      parameters:
        - in: query
          name: pageNumber
          schema:
            type: integer
            format: int32
        - in: query
          name: pageSize
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: All members
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Members' 
components:
  schemas:
    Sex:
      type: string
      enum:
        - MALE
        - FEMALE
        - OTHER
    Payment:
      type: string
      enum:
        - MONTHLY
        - ANNUALLY
        - NONE
    Role:
      type: string
      enum:
        - PASSANGER
        - DRIVER
        - MANAGER
        - ADMIN
    MemberStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
        - TO_BE_DELETED
    MemberApplicationStatus:
      type: string
      enum:
        - NEW
        - DATA_INVALID
        - APPLICATION_SUBMITTED
        - ACCEPTED
        - REJECTED
        - DUPLICATE
    MemberApplicationUpdate:
      type: string
      enum:
        - SAVE
        - ACCEPTED
        - REJECT
        - INQUIRY
    Page:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        number:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
    CountOfInprogressMemberOnboardings:
      type: object
      properties:
        count:
          type: integer
          format: int32
    CountOfActiveMembers: 
      type: object
      properties:
        count:
          type: integer
          format: int32
    MemberOnboardingApplications:
      type: object
      properties:
        page:
          $ref: '#/components/schemas/Page'
        applications:
          type: array
          items:
            $ref: '#/components/schemas/MemberApplication'
    Members:
      type: object
      properties:
        page:
          $ref: '#/components/schemas/Page'
        members:
          type: array
          items:
            $ref: '#/components/schemas/Member'
    UpdateMemberOnboarding:
      type: object
      properties:
        action:
          $ref: '#/components/schemas/MemberApplicationUpdate'
        taskId:
          type: string
        memberApplication:
          $ref: '#/components/schemas/MemberApplication'
    MemberApplication:
      type: object
      properties:
        id:
          type: string
        taskId:
          type: string
        status:
          $ref: '#/components/schemas/MemberApplicationStatus'
        memberId:
          type: int
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        title:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        birthdate:
          type: string
          format: date
        sex:
          $ref: '#/components/schemas/Sex'
        zip:
          type: string
        city:
          type: string
        street:
          type: string
        streetNumber:
          type: string
        phoneNumber:
          type: string
        preferNotificationsPerSms:
          type: boolean
        comment:
          type: string
        applicationComment:
          type: string
        initialRole:
          $ref: '#/components/schemas/Role'
    Member:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/MemberStatus'
        memberId:
          type: integer
          format: int32
        title:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        birthdate:
          type: string
          format: date
        sex:
          $ref: '#/components/schemas/Sex'
        zip:
          type: string
        city:
          type: string
        street:
          type: string
        streetNumber:
          type: string
        phoneNumber:
          type: string
        preferNotificationsPerSms:
          type: boolean
        payment:
          $ref: '#/components/schemas/Payment'
        iban:
          type: string
        comment:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
