openapi: 3.0.0
info:
  description: GUI API
  version: '1.0'
  title: gui
servers:
  - url: /api/v1.0

security:
  - JWT: []

paths:
  /gui/app-info:
    get:
      tags:
        - login
      summary: information about the current app
      operationId: appInformation
      responses:
        200:
          description: the app information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppInformation'
  /gui/oauth2-clients:
    get:
      tags:
        - login
      summary: a list of all available oauth2-clients
      operationId: oauth2Clients
      parameters:
        - in: header
          name: "User-Agent"
          schema:
            type: string
      responses:
        200:
          description: the oauth2-clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Oauth2Client'
  /gui/current-user:
    get:
      tags:
        - login
      summary: load current user from security context
      operationId: currentUser
      parameters:
        - in: header
          name: "X-Refresh-Token"
          schema:
            type: string
      responses:
        200:
          description: The user logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: No user logged in
    post:
      tags:
        - login
      summary: submit the token from native App login
      operationId: nativeAppLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NativeLogin'
      responses:
        200:
          description: The user logged in
        400:
          description: User not logged in
  /gui/member/application/take-over:
    put:
      tags:
        - onboarding
      summary: take-over the member application form
      operationId: takeoverMemberApplicationForm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: string
      responses:
        200:
          description: Take-over successfully
  /gui/member/application:
    get:
      tags:
        - onboarding
      summary: load the member application form
      operationId: loadMemberApplicationForm
      responses:
        200:
          description: Submission successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberApplicationForm'
    post:
      tags:
        - onboarding
      summary: submit the member application form
      operationId: submitMemberApplicationForm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberApplicationForm'
      responses:
        200:
          description: Submission successfully
          content:
            application/json:
              schema:
                type: string
        400:
          description: Some application values are not accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrors'
  /gui/member/{memberId}/prefer-notifications-per-sms:
    post:
      tags:
        - member
      summary: Set prefered way for notifications
      operationId: setPreferedWayForNotifications
      parameters:
        - in: path
          name: memberId
          required: true
          schema:
            type: integer
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: The setting was saved
        404:
          description: The member-id is unknown
  /gui/member/{memberId}/avatar:
    get:
      tags:
        - member
      summary: load avatar for given member id
      operationId: avatarOfMember
      parameters:
        - in: path
          name: memberId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The avatar as PNG-stream
          content:
            image/png:
              schema:
                type: string
                format: binary
        404:
          description: The member-id is unknown
    post:
      tags:
        - member
      summary: upload avatar for given member id
      operationId: uploadAvatar
      parameters:
        - in: path
          name: memberId
          required: true
          schema:
            type: integer
      requestBody:
        content:
          image/png:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: The avatar as PNG-stream was saved
  /gui/member/{memberId}:
    get:
      tags:
        - member
      summary: load details for given member id
      operationId: getMemberDetails
      parameters:
        - in: path
          name: memberId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The member details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'
        404:
          description: The member-id is unknown
  /gui/member/phone-code:
    put:
      tags:
        - member
      summary: Request a code sent to phone via SMS
      operationId: requestPhoneCode
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: The code was sent
        400:
          description: phone number is wrong format
        404:
          description: The member-id is unknown
    post:
      tags:
        - member
      summary: Changes the users phone number
      operationId: changePhoneNumber
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeBasedChange'
      responses:
        200:
          description: Number successfully changed
        400:
          description: phone number is wrong format
        404:
          description: The member-id is unknown
  /gui/member/email-code:
    put:
      tags:
        - member
      summary: Request a code sent via email
      operationId: requestEmailCode
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        200:
          description: The code was sent
        400:
          description: email address is wrong format
        404:
          description: The member-id is unknown
    post:
      tags:
        - member
      summary: Changes the users email address
      operationId: changeEmail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeBasedChange'
      responses:
        200:
          description: Email successfully changed
        400:
          description: Email is wrong format
        404:
          description: The member-id is unknown
  /gui/car-sharing/calendar:
    post:
      tags:
        - car-sharing
      summary: The calendar for car-sharing
      operationId: getCarSharingCalendar
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarSharingCalendarRequest'
      responses:
        200:
          description: The calander
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarSharingCalendar'
  /gui/car-sharing/{carId}/reservation:
    post:
      tags:
        - car-sharing
      summary: Take a reservation
      operationId: addCarSharingReservation
      parameters:
        - in: path
          name: carId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CarSharingReservation'
      responses:
        200:
          description: Reservation accepted
        400:
          description: Input parameters invalid
        404:
          description: Car not found
        409:
          description: Reservation declined due to other reservations
components:
  schemas:
    ValidationErrors:
      type: object
      additionalProperties: {}
    Sex:
      type: string
      enum:
        - MALE
        - FEMALE
        - OTHER
    Role:
      type: string
      enum:
        - PASSANGER
        - DRIVER
        - CAR
        - MANAGER
        - ADMIN
    UserStatus:
      type: string
      enum:
        - NEW
        - APPLICATION_SUBMITTED
        - DATA_INVALID
        - REJECTED
        - ACTIVE
        - INACTIVE
    CarSharingReservationType:
      type: string
      enum:
        - CS # shortcut of CarSharing
        - BLOCK
        - PS # shortcut of PassanagerService
    AppInformation:
      type: object
      properties:
        titleShort:
          type: string
        titleLong:
          type: string
        homepageUrl:
          type: string
        homepageServiceConditionsUrl:
          type: string
        contactEmailAddress:
          type: string
        version:
          type: string
    NativeLogin:
      type: object
      properties:
        clientId:
          type: string
        oauth2Id:
          type: string
        accessToken:
          type: string
    Oauth2Client:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        name:
          type: string
    CodeBasedChange:
      type: object
      properties:
        code:
          type: string
        value:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/UserStatus'
        memberId:
          type: int
        email:
          type: string
        name:
          type: string
        firstName:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        avatar:
          type: integer
          format: int64
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    Member:
      type: object
      properties:
        title:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        birthdate:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        zip:
          type: string
        city:
          type: string
        street:
          type: string
        streetNumber:
          type: string
        phoneNumber:
          type: string
        preferNotificationsPerSms:
          type: boolean
    MemberApplicationForm:
      type: object
      properties:
        applicationId:
          type: string
        memberId:
          type: integer
          format: int32
        taskId:
          type: string
        title:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        emailConfirmationCode:
          type: string
        birthdate:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        zip:
          type: string
        city:
          type: string
        street:
          type: string
        streetNumber:
          type: string
        phoneNumber:
          type: string
        phoneConfirmationCode:
          type: string
        preferNotificationsPerSms:
          type: boolean
        comment:
          type: string
        applicationComment:
          type: string
    CarSharingCalendarRequest:
      type: object
      properties:
        startsAt:
          type: string
          format: date-time
        endsAt:
          type: string
          format: date-time
        history:
          type: boolean
    CarSharingDriver:
      type: object
      properties:
        memberId:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        phoneNumber:
          type: string
    CarSharingCar:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        shortcut:
          type: string
        reservations:
          type: array
          items:
            $ref: '#/components/schemas/CarSharingReservation'
    CarSharingReservation:
      type: object
      properties:
        startsAt:
          type: string
          format: date-time
        endsAt:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/CarSharingReservationType'
        driverMemberId:
          type: integer
    CarSharingCalendar:
      type: object
      properties:
        drivers:
          type: array
          items:
            $ref: '#/components/schemas/CarSharingDriver'
        cars:
          type: array
          items:
            $ref: '#/components/schemas/CarSharingCar'
