openapi: 3.0.0
info:
  description: GUI API
  version: '1.0'
  title: gui
servers:
  - url: /api/v1.0

security:
  - JWT: []

paths:
  /gui/app-info:
    get:
      tags:
        - gui
      summary: information about the current app
      operationId: appInformation
      responses:
        200:
          description: the app information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppInformation'
  /gui/oauth2-clients:
    get:
      tags:
        - gui
      summary: a list of all available oauth2-clients
      operationId: oauth2Clients
      responses:
        200:
          description: the oauth2-clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Oauth2Client'
  /gui/current-user:
    get:
      tags:
        - gui
      summary: load current user from security context
      operationId: currentUser
      responses:
        200:
          description: The user logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: No user logged in
  /gui/drivers/text-messages:
    post:
      tags:
        - gui
      summary: Request text messages to be sent by mobile phone
      operationId: requestTextMessages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextMessageRequest'
      responses:
        200:
          description: The messages to be sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextMessages'
        400:
          description: email address is wrong format
        404:
          description: The member-id is unknown
  /gui/member/application/take-over:
    put:
      tags:
        - gui
      summary: take-over the member application form
      operationId: takeoverMemberApplicationForm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId:
                  type: string
      responses:
        200:
          description: Take-over successfully
  /gui/member/application:
    get:
      tags:
        - gui
      summary: load the member application form
      operationId: loadMemberApplicationForm
      responses:
        200:
          description: Submission successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberApplicationForm'
    post:
      tags:
        - gui
      summary: submit the member application form
      operationId: submitMemberApplicationForm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberApplicationForm'
      responses:
        200:
          description: Submission successfully
          content:
            application/json:
              schema:
                type: string
        400:
          description: Some application values are not accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrors'
  /gui/member/{memberId}/avatar:
    get:
      tags:
        - gui
      summary: load avatar for given member id
      operationId: avatarOfMember
      parameters:
        - in: path
          name: memberId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The avatar as PNG-stream
          content:
            image/png:
              schema:
                type: string
                format: binary
        404:
          description: The member-id is unknown
  /gui/member/request-phone-code:
    get:
      tags:
        - gui
      summary: Request a code sent to phone via SMS
      operationId: requestPhoneCode
      parameters:
        - in: query
          name: phoneNo
          required: true
          schema:
            type: string
      responses:
        200:
          description: The code was sent
        400:
          description: phone number is wrong format
        404:
          description: The member-id is unknown
  /gui/member/request-email-code:
    get:
      tags:
        - gui
      summary: Request a code sent via email
      operationId: requestEmailCode
      parameters:
        - in: query
          name: emailAddress
          required: true
          schema:
            type: string
      responses:
        200:
          description: The code was sent
        400:
          description: email address is wrong format
        404:
          description: The member-id is unknown
components:
  schemas:
    ValidationErrors:
      type: object
      additionalProperties: {}
    Sex:
      type: string
      enum:
        - MALE
        - FEMALE
        - OTHER
    Role:
      type: string
      enum:
        - PASSANGER
        - DRIVER
        - MANAGER
        - ADMIN
    UserStatus:
      type: string
      enum:
        - NEW
        - APPLICATION_SUBMITTED
        - DATA_INVALID
        - REJECTED
        - ACTIVE
        - INACTIVE
    AppInformation:
      type: object
      properties:
        titleShort:
          type: string
        titleLong:
          type: string
        homepageUrl:
          type: string
        homepageServiceConditionsUrl:
          type: string
        version:
          type: string
    TextMessageRequest:
      type: object
      properties:
        sender:
          type: string
    TextMessage:
      type: object
      properties:
        recipient:
          type: string
        content:
          type: string
    TextMessages:
      type: object
      properties:
        textMessages:
          type: array
          items:
            $ref: '#/components/schemas/TextMessage'
    Oauth2Client:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        name:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/UserStatus'
        memberId:
          type: int
        email:
          type: string
        name:
          type: string
        firstName:
          type: string
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    MemberApplicationForm:
      type: object
      properties:
        applicationId:
          type: string
        memberId:
          type: integer
          format: int32
        taskId:
          type: string
        title:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        emailConfirmationCode:
          type: string
        birthdate:
          type: string
        sex:
          $ref: '#/components/schemas/Sex'
        zip:
          type: string
        city:
          type: string
        street:
          type: string
        streetNumber:
          type: string
        phoneNumber:
          type: string
        phoneConfirmationCode:
          type: string
        preferNotificationsPerSms:
          type: boolean
        comment:
          type: string
        applicationComment:
          type: string
